cc_binary(
    name = "references",
    srcs = ["references.cpp"],
)

cc_binary(
    name = "pointers",
    srcs = ["pointers.cpp"],
)

cc_binary(
    name = "dynamic_memory",
    srcs = ["dynamic_memory.cpp"],
)
