cc_binary(
    name = "hello_world",
    srcs = ["hello_world.cpp"],
)

cc_binary(
    name = "conditionals",
    srcs = ["conditionals.cpp"],
)

cc_binary(
    name = "while_loop",
    srcs = ["while_loop.cpp"],
)

cc_binary(
    name = "for_loop",
    srcs = ["for_loop.cpp"],
)

cc_binary(
    name = "do_while_loop",
    srcs = ["do_while_loop.cpp"],
)
