cc_library(
    name = "homework",
    hdrs = ["vector.hpp"],
)

cc_test(
    name = "homework_test",
    srcs = ["test.cpp"],
    deps = [
        ":homework",
        "@com_google_googletest//:gtest_main",
    ],
)
