load("@rules_python//python:defs.bzl", "py_library")
load("@pip_deps//:requirements.bzl", pip_deps = "requirement")

py_library(
    name = "test_common",
    srcs = glob(["*.py"]),
    visibility = ["//visibility:public"],
)
