cc_binary(
    name = "functions",
    srcs = ["functions.cpp"],
    deps = ["//3rdparty/cpp:CLI11"],
)

cc_binary(
    name = "classes1",
    srcs = ["classes1.cpp"],
    deps = ["//3rdparty/cpp:CLI11"],
)

cc_binary(
    name = "classes2",
    srcs = ["classes2.cpp"],
    deps = ["//3rdparty/cpp:CLI11"],
)
