cc_binary(
    name = "bad_memory",
    srcs = ["bad_memory.cpp"],
)

cc_binary(
    name = "unique_ptr",
    srcs = ["unique_ptr.cpp"],
)

cc_binary(
    name = "shared_ptr",
    srcs = ["shared_ptr.cpp"],
)
