cc_binary(
    name = "vectors",
    srcs = ["vectors.cpp"],
)

cc_binary(
    name = "casts",
    srcs = ["casts.cpp"],
)

cc_binary(
    name = "iterator",
    srcs = ["iterator.cpp"],
)

cc_binary(
    name = "cmdline",
    srcs = ["cmdline.cpp"],
)

cc_binary(
    name = "cli_example",
    srcs = ["cli_example.cpp"],
    deps = ["//3rdparty/cpp:CLI11"],
)

cc_binary(
    name = "sort",
    srcs = ["sort.cpp"],
)
